print("before exception")
print(x)
print("after exception")

'''Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\PythonTesting\Day18Exceptions\Demo2.py", line 2, in <module>
    print(x)
          ^
NameError: name 'x' is not defined
before exception

Process finished with exit code 1'''